// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddUserRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type FindUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserRequest) Reset()         { *m = FindUserRequest{} }
func (m *FindUserRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserRequest) ProtoMessage()    {}
func (*FindUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *FindUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserRequest.Unmarshal(m, b)
}
func (m *FindUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserRequest.Marshal(b, m, deterministic)
}
func (m *FindUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserRequest.Merge(m, src)
}
func (m *FindUserRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserRequest.Size(m)
}
func (m *FindUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserRequest proto.InternalMessageInfo

func (m *FindUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResponse) Reset()         { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()    {}
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *AddUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResponse.Unmarshal(m, b)
}
func (m *AddUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResponse.Marshal(b, m, deterministic)
}
func (m *AddUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResponse.Merge(m, src)
}
func (m *AddUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddUserResponse.Size(m)
}
func (m *AddUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResponse proto.InternalMessageInfo

func (m *AddUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FindUserResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserResponse) Reset()         { *m = FindUserResponse{} }
func (m *FindUserResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserResponse) ProtoMessage()    {}
func (*FindUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *FindUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserResponse.Unmarshal(m, b)
}
func (m *FindUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserResponse.Marshal(b, m, deterministic)
}
func (m *FindUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserResponse.Merge(m, src)
}
func (m *FindUserResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserResponse.Size(m)
}
func (m *FindUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserResponse proto.InternalMessageInfo

func (m *FindUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FindUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FindUserResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *FindUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*AddUserRequest)(nil), "user.AddUserRequest")
	proto.RegisterType((*FindUserRequest)(nil), "user.FindUserRequest")
	proto.RegisterType((*AddUserResponse)(nil), "user.AddUserResponse")
	proto.RegisterType((*FindUserResponse)(nil), "user.FindUserResponse")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0x31, 0x4b, 0xc6, 0x30,
	0x14, 0xf4, 0xab, 0xd1, 0x4f, 0x1f, 0xd2, 0xca, 0xa3, 0x95, 0xd0, 0x49, 0x33, 0x88, 0x20, 0x54,
	0xd0, 0x45, 0x70, 0xd2, 0xc1, 0x1f, 0x50, 0x70, 0x71, 0x6b, 0xc9, 0x43, 0x03, 0x36, 0xa9, 0x4d,
	0x3b, 0xfa, 0xdf, 0xa5, 0x69, 0x62, 0x6d, 0x96, 0x70, 0x77, 0x5c, 0x8e, 0x7b, 0x07, 0x45, 0x3f,
	0x98, 0xd1, 0xdc, 0x4d, 0x96, 0x06, 0xf7, 0x54, 0x8e, 0x23, 0x9b, 0xb1, 0xb8, 0x86, 0xf4, 0x59,
	0xca, 0x37, 0x4b, 0x43, 0x4d, 0xdf, 0x13, 0xd9, 0x11, 0x73, 0x38, 0xea, 0x3f, 0x8d, 0x26, 0xbe,
	0xbb, 0xdc, 0xdd, 0x9c, 0xd6, 0x0b, 0x11, 0x57, 0x90, 0xbd, 0x2a, 0xbd, 0x31, 0xa6, 0x90, 0x28,
	0xe9, 0x5d, 0x89, 0x92, 0xe2, 0x16, 0xb2, 0xbf, 0x28, 0xdb, 0x1b, 0x6d, 0x09, 0x39, 0xec, 0x3b,
	0xb2, 0xb6, 0xf9, 0x08, 0x69, 0x81, 0x8a, 0x16, 0xce, 0xd7, 0x3c, 0xef, 0x8e, 0x02, 0x11, 0x81,
	0xe9, 0xa6, 0x23, 0x9e, 0x38, 0xc5, 0xe1, 0xb5, 0xdd, 0xe1, 0xbf, 0x76, 0xb3, 0x4a, 0x5d, 0xa3,
	0xbe, 0x38, 0x5b, 0x54, 0x47, 0xee, 0x7f, 0x80, 0xcd, 0xf9, 0xf8, 0x08, 0x7b, 0x5f, 0x0c, 0xf3,
	0xca, 0x2d, 0xb0, 0x3d, 0xb9, 0x2c, 0x22, 0x75, 0xe9, 0x23, 0x0e, 0xf0, 0x09, 0x4e, 0x42, 0x4b,
	0xf4, 0xa6, 0x68, 0x85, 0xf2, 0x22, 0x96, 0xc3, 0xe7, 0x97, 0xb3, 0x77, 0x58, 0x97, 0x6f, 0x8f,
	0x1d, 0x7e, 0xf8, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x7b, 0xfe, 0x07, 0x8e, 0x01, 0x00, 0x00,
}
